### ISSUE TITLE
nested progress bars in cli.py

### ISSUE THREAD

**Issue by ptits** [genmoai/models#39]
with progress_bar(type="tqdm"):
        final_frames = pipeline(**args)
        ...

FOR SINGLE GPU:

Timing load_text_encoder
Timing load_dit
Timing load_vae
Stage                   Time(s)    Percent
load_text_encoder          5.93      2.87%
load_dit                 193.06     93.39%
load_vae                   7.73      3.74%
Traceback (most recent call last):
  File "/home/jovyan/models/cli.py", line 152, in <module>
    generate_cli()
  File "/opt/conda/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/models/cli.py", line 138, in generate_cli
    output = generate_video(
             ^^^^^^^^^^^^^^^
  File "/home/jovyan/models/cli.py", line 94, in generate_video
    final_frames = pipeline(**args)
                   ^^^^^^^^^^^^^^^^
  File "/home/jovyan/models/genmo/mochi_preview/pipelines.py", line 536, in __call__
    with progress_bar(type="tqdm"), torch.inference_mode():
  File "/opt/conda/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/jovyan/models/genmo/lib/progress.py", line 78, in progress_bar
    raise RuntimeError("Nested progress bars are not supported")
RuntimeError: Nested progress bars are not supported

**Comment by ved-genmo** [comment]
should be fixed
