### ISSUE TITLE
diffusers support

### ISSUE THREAD

**Issue by feizc** [genmoai/models#41]
Hi, thanks for great works! 

I have used diffusers' script to convert CKPT, and it only took a few simple lines to generate excellent results.

A simple example as: 

```bash
from diffusers import MochiPipeline
from diffusers.utils import export_to_video

pipe = MochiPipeline.from_pretrained(model_path, torch_dtype=torch.bfloat16)
pipe.to("cuda")
prompt = "Close-up of a chameleon's eye, with its scaly skin changing color. Ultra high resolution 4k."
frames = pipe(prompt, 
    num_inference_steps=50, 
    guidance_scale=4.5,
    num_frames=61,
    generator=torch.Generator(device="cuda").manual_seed(42),
).frames[0]

export_to_video(frames, "mochi.mp4")
```

Huggingface ckpt can download from: 
https://huggingface.co/feizhengcong/mochi-1-preview-diffusers

Some results:

https://github.com/user-attachments/assets/8b7b6f32-c4e3-4d29-afe8-c4607ec216a7

https://github.com/user-attachments/assets/fc8f828a-5f46-4d9c-b7c7-2ba8a32d5718

**Comment by johnwick123f** [comment]
Thanks, one question I have is how fast is it? And on what device?

**Comment by feizc** [comment]
> Thanks, one question I have is how fast is it? And on what device?

It takes 4min to generate a 6s video in one A100, about 36G memmory.

![image](https://github.com/user-attachments/assets/b9c162c9-9490-4ec4-a216-6ad5faafe840)

![image](https://github.com/user-attachments/assets/a2ad26cc-a6d2-4acb-ab87-8cc14761b312)

**Comment by yyvhang** [comment]
thanks, which version of the diffuser could use it?

**Comment by zishen-ucap** [comment]
> > Thanks, one question I have is how fast is it? And on what device?
> 
> It takes 4min to generate a 6s video in one A100, about 36G memmory.
> 
> ![image](https://private-user-images.githubusercontent.com/37614046/381793742-b9c162c9-9490-4ec4-a216-6ad5faafe840.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NTQzODEsIm5iZiI6MTczMDQ1NDA4MSwicGF0aCI6Ii8zNzYxNDA0Ni8zODE3OTM3NDItYjljMTYyYzktOTQ5MC00ZWM0LWEyMTYtNmFkNWZhYWZlODQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDA5NDEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2MTkwZDM5ZTU4ODY5NTg3Y2E4OTFlZWQxMDVkNjYwYmU3NDFiN2MzMGIzNDA0YmY4OTI3MmEwYjhhYjIyNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cRrXfHmFmsmbsAAiXdEVrARxcjqvClpuJWdBBkkyc54)
> 
> ![image](https://private-user-images.githubusercontent.com/37614046/381793844-a2ad26cc-a6d2-4acb-ab87-8cc14761b312.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NTQzODEsIm5iZiI6MTczMDQ1NDA4MSwicGF0aCI6Ii8zNzYxNDA0Ni8zODE3OTM4NDQtYTJhZDI2Y2MtYTZkMi00YWNiLWFiODctOGNjMTQ3NjFiMzEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDA5NDEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyNDRjNmM1YjRmYTA4YTVjMzgzNjk1ODY3NDYzMTk4OGE4MzM4ZWQ0ZTJjMDYwOWJkODNlNDU0M2UzZTU2ZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qt2Gbt_7mCfk84Gl0tmHiY_Fr9stoi-UP0y5ZlgoA_8)

我推理发现和genmo的不一样，而且推理同样的帧数和去噪步数，发现差不多要26分钟。。。我不知道是不是我放的参数有问题，你能帮我看一下吗？
`from diffusers import MochiPipeline
from diffusers.utils import export_to_video
import torch

model_path = "mochi-1-preview-diffusers"

pipe = MochiPipeline.from_pretrained(model_path, torch_dtype=torch.bfloat16)
pipe.to("cuda")
prompt = "A stark white cat with piercing green eyes stealthily creeps along the glossy, dark wooden floorboards of an opulent European-style parlor. Intricate wainscoting and luxurious wallpaper frame the scene. In a heart-racing moment, the cat pounces with precision towards a unsuspecting brown mouse near an ornate, mahogany furniture piece. The high-definition footage captures every nuanced movement, from the flutter of the cat's whiskers to the mouse's flickering tail, as an antique grandfather clock ticks rhythmically in the background. The elegant room's vintage charm contrasts with the primal, instinctive encounter unfolding within it."
frames = pipe(prompt, 
    num_inference_steps=99, 
    guidance_scale=4.5,
    num_frames=163,
    generator=torch.Generator(device="cuda").manual_seed(42),
).frames[0]

export_to_video(frames, "mochi.mp4")`

https://github.com/user-attachments/assets/b9cec603-5ae8-40cd-bec5-9bd9ecfb6479

这个是diffusers的参数和推理结果

`@click.command()
@click.option("--prompt", required=True, help="Prompt for video generation.")
@click.option(
    "--negative_prompt", default="", help="Negative prompt for video generation."
)
@click.option("--width", default=848, type=int, help="Width of the video.")
@click.option("--height", default=480, type=int, help="Height of the video.")
@click.option("--num_frames", default=163, type=int, help="Number of frames.")
@click.option("--seed", default=42, type=int, help="Random seed.")
@click.option("--cfg_scale", default=4.5, type=float, help="CFG Scale.")
@click.option(
    "--num_steps", default=100, type=int, help="Number of inference steps."
)
@click.option("--model_dir", required=True, help="Path to the model directory.")`


https://github.com/user-attachments/assets/3276da72-3bea-493a-8141-a267c2813af5

[https://github.com/genmoai/models/blob/main/demos/cli.py](url)
这个是genmo原版的参数和推理结果

**Comment by feizc** [comment]
Hi, you can take a look at other issues. The author said they would "up sample" the prompt. This has a significant impact on the final generated result. A simple approach is to use LLM expand and generate more beautiful videos:)

> > > Thanks, one question I have is how fast is it? And on what device?
> > 
> > 
> > It takes 4min to generate a 6s video in one A100, about 36G memmory.
> > ![image](https://private-user-images.githubusercontent.com/37614046/381793742-b9c162c9-9490-4ec4-a216-6ad5faafe840.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NTQzODEsIm5iZiI6MTczMDQ1NDA4MSwicGF0aCI6Ii8zNzYxNDA0Ni8zODE3OTM3NDItYjljMTYyYzktOTQ5MC00ZWM0LWEyMTYtNmFkNWZhYWZlODQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDA5NDEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2MTkwZDM5ZTU4ODY5NTg3Y2E4OTFlZWQxMDVkNjYwYmU3NDFiN2MzMGIzNDA0YmY4OTI3MmEwYjhhYjIyNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cRrXfHmFmsmbsAAiXdEVrARxcjqvClpuJWdBBkkyc54)
> > ![image](https://private-user-images.githubusercontent.com/37614046/381793844-a2ad26cc-a6d2-4acb-ab87-8cc14761b312.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NTQzODEsIm5iZiI6MTczMDQ1NDA4MSwicGF0aCI6Ii8zNzYxNDA0Ni8zODE3OTM4NDQtYTJhZDI2Y2MtYTZkMi00YWNiLWFiODctOGNjMTQ3NjFiMzEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDA5NDEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyNDRjNmM1YjRmYTA4YTVjMzgzNjk1ODY3NDYzMTk4OGE4MzM4ZWQ0ZTJjMDYwOWJkODNlNDU0M2UzZTU2ZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qt2Gbt_7mCfk84Gl0tmHiY_Fr9stoi-UP0y5ZlgoA_8)
> 
> ![C9091E61-71BF-43e9-A223-56951D2552C8](https://private-user-images.githubusercontent.com/172017586/382248214-a6e53d34-c244-4eb3-a3b6-bb6f1281b227.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NTY1NjIsIm5iZiI6MTczMDQ1NjI2MiwicGF0aCI6Ii8xNzIwMTc1ODYvMzgyMjQ4MjE0LWE2ZTUzZDM0LWMyNDQtNGViMy1hM2I2LWJiNmYxMjgxYjIyNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMVQxMDE3NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZDAwYzExN2RhNTRhYzUzZWYxNjcxMjZjZTEyMjg5M2VkY2EwMWRlZDRlNjY0ZTkxMmZhNzk4Y2Y4NWZiNWQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.HVFl5ijNr8KNyWwhiETaAYixIfEczCHKFZ6Xiiby4xo)
> 
> 我发现diffusers的推理结果和genmo的不一样，而且推理同样的帧数和去噪步数，发现差不多要26分钟。。。我不知道是不是我放的参数有问题，你能帮我看一下吗？
> 
> ```
> from diffusers import MochiPipeline
> from diffusers.utils import export_to_video
> import torch
> 
> model_path = "mochi-1-preview-diffusers"
> 
> pipe = MochiPipeline.from_pretrained(model_path, torch_dtype=torch.bfloat16)
> pipe.to("cuda")
> prompt = "A stark white cat with piercing green eyes stealthily creeps along the glossy, dark wooden floorboards of an opulent European-style parlor. Intricate wainscoting and luxurious wallpaper frame the scene. In a heart-racing moment, the cat pounces with precision towards a unsuspecting brown mouse near an ornate, mahogany furniture piece. The high-definition footage captures every nuanced movement, from the flutter of the cat's whiskers to the mouse's flickering tail, as an antique grandfather clock ticks rhythmically in the background. The elegant room's vintage charm contrasts with the primal, instinctive encounter unfolding within it."
> frames = pipe(prompt, 
>     num_inference_steps=99, 
>     guidance_scale=4.5,
>     num_frames=163,
>     generator=torch.Generator(device="cuda").manual_seed(42),
> ).frames[0]
> 
> export_to_video(frames, "mochi.mp4")
> ```
> 
>  mochi.mp4 
> 这个是diffusers的参数和推理结果
> 
> `@click.command() @click.option("--prompt", required=True, help="Prompt for video generation.") @click.option( "--negative_prompt", default="", help="Negative prompt for video generation." ) @click.option("--width", default=848, type=int, help="Width of the video.") @click.option("--height", default=480, type=int, help="Height of the video.") @click.option("--num_frames", default=163, type=int, help="Number of frames.") @click.option("--seed", default=42, type=int, help="Random seed.") @click.option("--cfg_scale", default=4.5, type=float, help="CFG Scale.") @click.option( "--num_steps", default=100, type=int, help="Number of inference steps." ) @click.option("--model_dir", required=True, help="Path to the model directory.")`
> 
>  output.mp4 
> [https://github.com/genmoai/models/blob/main/demos/cli.py](url) 这个是genmo原版的参数和推理结果

**Comment by LPengYang** [comment]
> > Thanks, one question I have is how fast is it? And on what device?
> 
> It takes 4min to generate a 6s video in one A100, about 36G memmory.
> 
> ![image](https://private-user-images.githubusercontent.com/37614046/381793742-b9c162c9-9490-4ec4-a216-6ad5faafe840.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2MjY3NTAsIm5iZiI6MTczMDYyNjQ1MCwicGF0aCI6Ii8zNzYxNDA0Ni8zODE3OTM3NDItYjljMTYyYzktOTQ5MC00ZWM0LWEyMTYtNmFkNWZhYWZlODQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAzVDA5MzQxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4ZDcyNTgzYWE0NjhlYmM2ZWFlMTEwZTY1ZTAxNWEyNTRlNWQ3YzA1YWYyNGM2MWU0Y2M2OTYyMTUwMDgxYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NK0uc08jR6doR9CSS0EFLDreKhZp52ZVdDt4c82TDsI)
> 
> ![image](https://private-user-images.githubusercontent.com/37614046/381793844-a2ad26cc-a6d2-4acb-ab87-8cc14761b312.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2MjY3NTAsIm5iZiI6MTczMDYyNjQ1MCwicGF0aCI6Ii8zNzYxNDA0Ni8zODE3OTM4NDQtYTJhZDI2Y2MtYTZkMi00YWNiLWFiODctOGNjMTQ3NjFiMzEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAzVDA5MzQxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0MTA4Zjg0MmUzNGM5OTNhNGEyOTQyY2MwY2QzM2FhYWJiN2FjYTZlNjc5OWY0NzE5ODZiZTY4M2RlMWExYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.o7eXNQDY4Tqno3yru3DzozUr7bD8Lq4X69Ch7RqNlwk)

Hello, it is obseved that the file size in diffusers is only about half of vanilla version, which cases such difference?

**Comment by HanLiii** [comment]
Hi @feizc , thanks for great works!

I failed to load the pipeline using following code:

from diffusers import MochiPipeline
import torch

pipe = MochiPipeline.from_pretrained("feizhengcong/mochi-1-preview-diffusers", torch_dtype=torch.bfloat16)
pipe.to("cuda")

The following is the error message:

Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.50it/s]
Loading pipeline components...:  60%|██████████████████████████████████████████████████████████▊                                       | 3/5 [00:59<00:39, 19.70s/it]
Traceback (most recent call last):
  File "/data/hli358/envs/mochi/lib/python3.10/site-packages/diffusers/models/model_loading_utils.py", line 140, in load_state_dict
    file_extension = os.path.basename(checkpoint_file).split(".")[-1]
  File "/data/hli358/envs/mochi/lib/python3.10/posixpath.py", line 142, in basename
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/hli358/han/mochi/download.py", line 4, in <module>
    pipe = MochiPipeline.from_pretrained("feizhengcong/mochi-1-preview-diffusers", torch_dtype=torch.bfloat16)
  File "/data/hli358/envs/mochi/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/data/hli358/envs/mochi/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 896, in from_pretrained
    loaded_sub_model = load_sub_model(
  File "/data/hli358/envs/mochi/lib/python3.10/site-packages/diffusers/pipelines/pipeline_loading_utils.py", line 704, in load_sub_model
    loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
  File "/data/hli358/envs/mochi/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/data/hli358/envs/mochi/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 940, in from_pretrained
    state_dict = load_state_dict(model_file, variant=variant)
  File "/data/hli358/envs/mochi/lib/python3.10/site-packages/diffusers/models/model_loading_utils.py", line 152, in load_state_dict
    with open(checkpoint_file) as f:
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by zishen-ucap** [comment]
我能理解的是提示词优化吗？但是我发现好像把提示词丢进t5前，并没有做其他处理
```
def get_conditioning(self, prompts, *, zero_last_n_prompts: int):
        B = len(prompts)
        assert (
            0 <= zero_last_n_prompts <= B
        ), f"zero_last_n_prompts should be between 0 and {B}, got {zero_last_n_prompts}"
        tokenize_kwargs = dict(
            prompt=prompts,
            padding="max_length",
            return_tensors="pt",
            truncation=True,
        )
        print(f'丢进t5前的提示词：{prompts}')
        t5_toks = self.t5_tokenizer(**tokenize_kwargs, max_length=MAX_T5_TOKEN_LENGTH)
```
得到的结果是：
`(T2VSynthMochiModel pid=616962) 丢进t5前的提示词：["A stark white cat with piercing green eyes stealthily creeps along the glossy, dark wooden floorboards of an opulent European-style parlor. Intricate wainscoting and luxurious wallpaper frame the scene. In a heart-racing moment, the cat pounces with precision towards a unsuspecting brown mouse near an ornate, mahogany furniture piece. The high-definition footage captures every nuanced movement, from the flutter of the cat's whiskers to the mouse's flickering tail, as an antique grandfather clock ticks rhythmically in the background. The elegant room's vintage charm contrasts with the primal, instinctive encounter unfolding within it.", ''] [repeated 3x across cluster]`

> Hi, you can take a look at other issues. The author said they would "up sample" the prompt. This has a significant impact on the final generated result. A simple approach is to use LLM expand and generate more beautiful videos:)
> 
> > > > Thanks, one question I have is how fast is it? And on what device?
> > > 
> > > 
> > > It takes 4min to generate a 6s video in one A100, about 36G memmory.
> > > ![image](https://private-user-images.githubusercontent.com/37614046/381793742-b9c162c9-9490-4ec4-a216-6ad5faafe840.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NTQzODEsIm5iZiI6MTczMDQ1NDA4MSwicGF0aCI6Ii8zNzYxNDA0Ni8zODE3OTM3NDItYjljMTYyYzktOTQ5MC00ZWM0LWEyMTYtNmFkNWZhYWZlODQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDA5NDEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2MTkwZDM5ZTU4ODY5NTg3Y2E4OTFlZWQxMDVkNjYwYmU3NDFiN2MzMGIzNDA0YmY4OTI3MmEwYjhhYjIyNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cRrXfHmFmsmbsAAiXdEVrARxcjqvClpuJWdBBkkyc54)
> > > ![image](https://private-user-images.githubusercontent.com/37614046/381793844-a2ad26cc-a6d2-4acb-ab87-8cc14761b312.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NTQzODEsIm5iZiI6MTczMDQ1NDA4MSwicGF0aCI6Ii8zNzYxNDA0Ni8zODE3OTM4NDQtYTJhZDI2Y2MtYTZkMi00YWNiLWFiODctOGNjMTQ3NjFiMzEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDA5NDEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyNDRjNmM1YjRmYTA4YTVjMzgzNjk1ODY3NDYzMTk4OGE4MzM4ZWQ0ZTJjMDYwOWJkODNlNDU0M2UzZTU2ZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qt2Gbt_7mCfk84Gl0tmHiY_Fr9stoi-UP0y5ZlgoA_8)
> > 
> > 
> > ![C9091E61-71BF-43e9-A223-56951D2552C8](https://private-user-images.githubusercontent.com/172017586/382248214-a6e53d34-c244-4eb3-a3b6-bb6f1281b227.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NTY1NjIsIm5iZiI6MTczMDQ1NjI2MiwicGF0aCI6Ii8xNzIwMTc1ODYvMzgyMjQ4MjE0LWE2ZTUzZDM0LWMyNDQtNGViMy1hM2I2LWJiNmYxMjgxYjIyNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMVQxMDE3NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZDAwYzExN2RhNTRhYzUzZWYxNjcxMjZjZTEyMjg5M2VkY2EwMWRlZDRlNjY0ZTkxMmZhNzk4Y2Y4NWZiNWQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.HVFl5ijNr8KNyWwhiETaAYixIfEczCHKFZ6Xiiby4xo)
> > 我发现diffusers的推理结果和genmo的不一样，而且推理同样的帧数和去噪步数，发现差不多要26分钟。。。我不知道是不是我放的参数有问题，你能帮我看一下吗？
> > ```
> > from diffusers import MochiPipeline
> > from diffusers.utils import export_to_video
> > import torch
> > 
> > model_path = "mochi-1-preview-diffusers"
> > 
> > pipe = MochiPipeline.from_pretrained(model_path, torch_dtype=torch.bfloat16)
> > pipe.to("cuda")
> > prompt = "A stark white cat with piercing green eyes stealthily creeps along the glossy, dark wooden floorboards of an opulent European-style parlor. Intricate wainscoting and luxurious wallpaper frame the scene. In a heart-racing moment, the cat pounces with precision towards a unsuspecting brown mouse near an ornate, mahogany furniture piece. The high-definition footage captures every nuanced movement, from the flutter of the cat's whiskers to the mouse's flickering tail, as an antique grandfather clock ticks rhythmically in the background. The elegant room's vintage charm contrasts with the primal, instinctive encounter unfolding within it."
> > frames = pipe(prompt, 
> >     num_inference_steps=99, 
> >     guidance_scale=4.5,
> >     num_frames=163,
> >     generator=torch.Generator(device="cuda").manual_seed(42),
> > ).frames[0]
> > 
> > export_to_video(frames, "mochi.mp4")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > mochi.mp4
> > 这个是diffusers的参数和推理结果
> > `@click.command() @click.option("--prompt", required=True, help="Prompt for video generation.") @click.option( "--negative_prompt", default="", help="Negative prompt for video generation." ) @click.option("--width", default=848, type=int, help="Width of the video.") @click.option("--height", default=480, type=int, help="Height of the video.") @click.option("--num_frames", default=163, type=int, help="Number of frames.") @click.option("--seed", default=42, type=int, help="Random seed.") @click.option("--cfg_scale", default=4.5, type=float, help="CFG Scale.") @click.option( "--num_steps", default=100, type=int, help="Number of inference steps." ) @click.option("--model_dir", required=True, help="Path to the model directory.")`
> > output.mp4
> > [https://github.com/genmoai/models/blob/main/demos/cli.py](url) 这个是genmo原版的参数和推理结果

**Comment by feizc** [comment]
Hi, @HanLiii , since vae encoder is provided, the convert script is updated and i re-upload the ckpts. You can try now :) 

> Hi @feizc , thanks for great works!
> 
> I failed to load the pipeline using following code:
> 
> ```
> from diffusers import MochiPipeline
> import torch
> 
> pipe = MochiPipeline.from_pretrained("feizhengcong/mochi-1-preview-diffusers", torch_dtype=torch.bfloat16)
> pipe.to("cuda")
> ```
> 
> The following is the error message:
> 
> ```
> Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.50it/s]
> Loading pipeline components...:  60%|██████████████████████████████████████████████████████████▊                                       | 3/5 [00:59<00:39, 19.70s/it]
> Traceback (most recent call last):
>   File "/data/hli358/envs/mochi/lib/python3.10/site-packages/diffusers/models/model_loading_utils.py", line 140, in load_state_dict
>     file_extension = os.path.basename(checkpoint_file).split(".")[-1]
>   File "/data/hli358/envs/mochi/lib/python3.10/posixpath.py", line 142, in basename
>     p = os.fspath(p)
> TypeError: expected str, bytes or os.PathLike object, not NoneType
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/data/hli358/han/mochi/download.py", line 4, in <module>
>     pipe = MochiPipeline.from_pretrained("feizhengcong/mochi-1-preview-diffusers", torch_dtype=torch.bfloat16)
>   File "/data/hli358/envs/mochi/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
>     return fn(*args, **kwargs)
>   File "/data/hli358/envs/mochi/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 896, in from_pretrained
>     loaded_sub_model = load_sub_model(
>   File "/data/hli358/envs/mochi/lib/python3.10/site-packages/diffusers/pipelines/pipeline_loading_utils.py", line 704, in load_sub_model
>     loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
>   File "/data/hli358/envs/mochi/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
>     return fn(*args, **kwargs)
>   File "/data/hli358/envs/mochi/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 940, in from_pretrained
>     state_dict = load_state_dict(model_file, variant=variant)
>   File "/data/hli358/envs/mochi/lib/python3.10/site-packages/diffusers/models/model_loading_utils.py", line 152, in load_state_dict
>     with open(checkpoint_file) as f:
> TypeError: expected str, bytes or os.PathLike object, not NoneType
> ```

**Comment by chenyzh28** [comment]
![image](https://github.com/user-attachments/assets/d69a363d-9739-448c-9058-1bb9c4745d6c)
Hi, I met a problem when I use diffusers, do you know why? My diffusers version is 0.31.0.
