### ISSUE TITLE
MochiSingleGPUPipeline.__init__() got an unexpected keyword argument 'tiled_decode'

### ISSUE THREAD

**Issue by Kaki-In** [genmoai/models#49]
I get this error when I try to generate a video:

```
Traceback (most recent call last):
  File "/home/kaki/Documents/models/.venv/lib/python3.10/site-packages/gradio/queueing.py", line 624, in process_events
    response = await route_utils.call_process_api(
  File "/home/kaki/Documents/models/.venv/lib/python3.10/site-packages/gradio/route_utils.py", line 323, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/kaki/Documents/models/.venv/lib/python3.10/site-packages/gradio/blocks.py", line 2018, in process_api
    result = await self.call_function(
  File "/home/kaki/Documents/models/.venv/lib/python3.10/site-packages/gradio/blocks.py", line 1567, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "/home/kaki/Documents/models/.venv/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/kaki/Documents/models/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
  File "/home/kaki/Documents/models/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 943, in run
    result = context.run(func, *args)
  File "/home/kaki/Documents/models/.venv/lib/python3.10/site-packages/gradio/utils.py", line 846, in wrapper
    response = f(*args, **kwargs)
  File "/home/kaki/Documents/models/demos/cli.py", line 66, in generate_video
    load_model()
  File "/home/kaki/Documents/models/demos/cli.py", line 53, in load_model
    pipeline = klass(**kwargs)
TypeError: MochiSingleGPUPipeline.__init__() got an unexpected keyword argument 'tiled_decode'
```

What should I do?

**Comment by ved-genmo** [comment]
should be fixed now

**Comment by Kaki-In** [comment]
It seems really slow, even if I have a nvidia GPU. Did I miss something?
